In [53]:
import torch
from torch import nn
import numpy as np
import os

In [54]:
target_folder = 'pretrain/rotate/RotatE_FB15k-237-betae_0/'

In [55]:
!ls 'pretrain/rotate/RotatE_FB15k-237-betae_0/'

checkpoint   entity_embedding.npy    train.log
config.json  relation_embedding.npy


In [58]:
entity_emb = np.load(os.path.join(target_folder, 'entity_embedding.npy'))

In [61]:
relation_emb = np.load(os.path.join(target_folder, 'relation_embedding.npy'))
relation_emb.shape

(474, 1000)

In [62]:
state_dict = torch.load(os.path.join(target_folder, 'checkpoint'), map_location='cpu')

In [63]:
state_dict['model_state_dict']['entity_embedding'].shape

torch.Size([14505, 2000])

In [64]:
state_dict['model_state_dict']['relation_embedding'].shape

torch.Size([474, 1000])

In [65]:
state_dict['model_state_dict']

OrderedDict([('gamma', tensor([9.])),
             ('embedding_range', tensor([0.0110])),
             ('entity_embedding',
              tensor([[ 0.0093,  0.0084,  0.0005,  ...,  0.0154, -0.0132,  0.0026],
                      [-0.0054,  0.0029, -0.0055,  ..., -0.0172,  0.0084,  0.0008],
                      [-0.0081,  0.0110,  0.0009,  ..., -0.0094,  0.0192, -0.0003],
                      ...,
                      [-0.0081,  0.0103, -0.0052,  ..., -0.0153, -0.0078, -0.0086],
                      [ 0.0123, -0.0030, -0.0186,  ...,  0.0192,  0.0010, -0.0174],
                      [ 0.0123, -0.0031,  0.0079,  ...,  0.0204, -0.0019, -0.0190]])),
             ('relation_embedding',
              tensor([[-0.0131, -0.0054,  0.0123,  ...,  0.0081, -0.0105,  0.0020],
                      [-0.0089,  0.0054,  0.0097,  ..., -0.0081,  0.0105, -0.0018],
                      [-0.0045,  0.0015, -0.0033,  ...,  0.0094,  0.0095, -0.0102],
                      ...,
                      [-0.0

In [25]:
state_dict['model_state_dict']

OrderedDict([('gamma', tensor([9.])),
             ('embedding_range', tensor([0.0110])),
             ('entity_embedding',
              tensor([[-2.1652e-03,  7.5591e-03,  9.4673e-03,  ..., -3.3301e-03,
                       -4.6427e-03,  1.8681e-03],
                      [ 9.7612e-03, -2.9553e-03, -2.6151e-03,  ...,  1.5460e-03,
                       -3.1212e-04, -3.5080e-03],
                      [-7.3657e-04,  6.1092e-03, -1.1593e-02,  ..., -8.2226e-04,
                        1.2900e-02,  1.8024e-02],
                      ...,
                      [ 1.4710e-02,  2.3520e-02,  8.6379e-03,  ...,  1.2705e-02,
                        4.5488e-03,  2.4548e-02],
                      [-2.6629e-03, -2.2561e-03,  1.7146e-05,  ...,  1.0072e-02,
                       -1.2170e-03, -6.4612e-03],
                      [-2.6907e-03, -3.4126e-03,  5.6558e-03,  ...,  9.9613e-03,
                       -1.9917e-02, -8.2948e-03]])),
             ('relation_embedding',
              tensor([[-

In [29]:
import json
with open("data/FB15k-237-betae/kgindex.json", 'rt') as f:
    kgindex = json.load(f)

In [31]:
len(kgindex['r'])

474

In [32]:
model_state_dict = state_dict['model_state_dict']

In [72]:
transformed_state_dict = {}

In [73]:
transformed_state_dict['_entity_embedding'] = model_state_dict['entity_embedding']

In [79]:
pi = 3.14159265358979323846

phase_relation = model_state_dict['relation_embedding'] / (model_state_dict['embedding_range'] / pi)
re_relation = torch.cos(phase_relation)
im_relation = torch.sin(phase_relation)
rel_emb = torch.cat([re_relation, im_relation], dim=-1)

In [80]:
rel_emb

tensor([[-0.5619, -0.7245, -0.7569,  ...,  0.8989,  0.6289, -0.9707],
        [-0.5622, -0.7246, -0.7554,  ..., -0.8946, -0.6228,  0.9668],
        [ 0.9649,  0.9743, -0.3250,  ...,  0.9810, -0.9261,  0.0162],
        ...,
        [-0.6727, -0.6274,  0.1532,  ..., -0.7207, -0.9891, -0.5119],
        [-0.8803, -0.4982,  0.9401,  ...,  0.9026, -0.9576,  0.9105],
        [ 0.8442,  0.5355,  0.4591,  ...,  0.0038, -0.4992,  0.3647]])

In [81]:
transformed_state_dict['_relation_embedding'] = rel_emb

In [82]:
transformed_state_dict

{'_entity_embedding': tensor([[-2.1652e-03,  7.5591e-03,  9.4673e-03,  ..., -3.3301e-03,
          -4.6427e-03,  1.8681e-03],
         [ 9.7612e-03, -2.9553e-03, -2.6151e-03,  ...,  1.5460e-03,
          -3.1212e-04, -3.5080e-03],
         [-7.3657e-04,  6.1092e-03, -1.1593e-02,  ..., -8.2226e-04,
           1.2900e-02,  1.8024e-02],
         ...,
         [ 1.4710e-02,  2.3520e-02,  8.6379e-03,  ...,  1.2705e-02,
           4.5488e-03,  2.4548e-02],
         [-2.6629e-03, -2.2561e-03,  1.7146e-05,  ...,  1.0072e-02,
          -1.2170e-03, -6.4612e-03],
         [-2.6907e-03, -3.4126e-03,  5.6558e-03,  ...,  9.9613e-03,
          -1.9917e-02, -8.2948e-03]]),
 '_relation_embedding': tensor([[-0.5619, -0.7245, -0.7569,  ...,  0.8989,  0.6289, -0.9707],
         [-0.5622, -0.7246, -0.7554,  ..., -0.8946, -0.6228,  0.9668],
         [ 0.9649,  0.9743, -0.3250,  ...,  0.9810, -0.9261,  0.0162],
         ...,
         [-0.6727, -0.6274,  0.1532,  ..., -0.7207, -0.9891, -0.5119],
         [-0

In [83]:
torch.save(transformed_state_dict, 'pretrain/rotate/FB15k-237-rotate.pt')

In [26]:
from src.structure.neural_binary_predicate import NeuralBinaryPredicate

In [ ]:
class RotatE(NeuralBinaryPredicate, nn.Module):
    def __init__(self,
                 num_entities: int,
                 num_relations: int,
                 embedding_dim: int,
                 scale: float = 1,
                 init_size: float = 1e-3,
                 device = 'cpu', **kwargs):
        super(ComplEx, self).__init__()

        self.num_entities = num_entities
        self.num_relations = num_relations
        self.embedding_dim = embedding_dim
        self.device = device
        self.scale = scale

        self._entity_embedding = nn.Embedding(num_entities, 2*embedding_dim)
        self._entity_embedding.weight.data *= init_size

        self._relation_embedding = nn.Embedding(num_relations, 2*embedding_dim)
        self._relation_embedding.weight.data *= init_size

    @property
    def entity_embedding(self):
        return self._entity_embedding.weight

    @property
    def relation_embedding(self):
        return self._relation_embedding.weight


    def embedding_score(self, head_emb, rel_emb, tail_emb):
        # lhs = head_emb[..., :self.rank], head_emb[..., self.rank:]
        # rel = rel_emb[..., :self.rank],  rel_emb[..., self.rank:]
        # rhs = tail_emb[..., :self.rank], tail_emb[..., self.rank:]
        # return torch.sum(
        #     (lhs[0] * rel[0] - lhs[1] * rel[1]) * rhs[0] +
        #     (lhs[0] * rel[1] + lhs[1] * rel[0]) * rhs[1],
        #     dim=-1)
        est_tail = self.estimate_tail_emb(head_emb, rel_emb)
        return self.entity_pair_scoring(est_tail, tail_emb)

    def score2truth_value(self, score):
        return torch.sigmoid(score / self.scale)

    def estimate_tail_emb(self, head_emb, rel_emb):
        lhs = head_emb[:, :self.embedding_dim], head_emb[:, self.embedding_dim:]
        rel = rel_emb[:, :self.embedding_dim], rel_emb[:, self.embedding_dim:]

        return torch.cat([
            lhs[0] * rel[0] - lhs[1] * rel[1],
            lhs[0] * rel[1] + lhs[1] * rel[0]
        ], 1)

    def estimate_head_emb(self, tail_emb, rel_emb):
        rhs = tail_emb[:, :self.embedding_dim], tail_emb[:, self.embedding_dim:]
        rel = rel_emb[:, :self.embedding_dim], -rel_emb[:, self.embedding_dim:]

        return torch.cat([
            rhs[0] * rel[0] - rhs[1] * rel[1],
            rhs[0] * rel[1] + rhs[1] * rel[0]
        ], 1)

    def estiamte_rel_emb(self, head_emb, tail_emb):
        lhs = head_emb[:, :self.embedding_dim], head_emb[:, self.embedding_dim:]
        rhs = tail_emb[:, :self.embedding_dim], tail_emb[:, self.embedding_dim:]

        return torch.cat([
            lhs[0] * rhs[0] + lhs[1] * rhs[1],
            lhs[0] * rhs[1] - lhs[1] * rhs[0]
        ], 1)

    def get_relation_emb(self, relation_id_or_tensor):
        rel_id = torch.tensor(relation_id_or_tensor, device=self.device)
        return self._relation_embedding(rel_id)

    def get_entity_emb(self, entity_id_or_tensor):
        ent_id = torch.tensor(entity_id_or_tensor, device=self.device)
        return self._entity_embedding(ent_id)

    def entity_pair_scoring(self, emb1, emb2):
        scores = torch.sum(emb1 * emb2, dim=-1)
        return scores
